<br>
<b><font size=12> 4. ADFGVX/ADFGX SYSTEM

## Steps:

1. Create <i>Polybius</i> table with key.
2. Replace letters in text according to table.
3. Build a columnar matrix and fill with replaced text.
4. Order columnar matrix, with headers in alphabetical order and read output in columns.

In [1]:
import pandas as pd

In [24]:
abc=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

def create_polybius(key,numbers=True):
    begin=list(dict.fromkeys([letter for letter in key]))
    alphabet=begin+[letter for letter in abc if letter not in begin]
    if numbers:
        for number,letter in enumerate(['J']+abc[:9]):
            letter_index=alphabet.index(letter)
            alphabet.insert(letter_index+1, str(number))
        table=pd.DataFrame([alphabet[x:x+6] for x in range(0,len(alphabet),6)],columns=['A','D','F','G','V','X'],index=['A','D','F','G','V','X'])
    else:
        letter_index=alphabet.index('J')
        alphabet=alphabet[:letter_index]+alphabet[letter_index+1:]
        letter_index=alphabet.index('I')
        alphabet[letter_index]='I/J'
        table=pd.DataFrame([alphabet[x:x+5] for x in range(0,len(alphabet),5)],columns=['A','D','F','G','X'],index=['A','D','F','G','X'])
    return table

def cypher_table(text, table):
    text_joined="".join("".join(text.split('.')).split()).upper()
    cypher_list=[]
    for letter in text_joined:
        for column in table.columns:
            column_bool=table[column].str.find(letter)>-1
            if column_bool.sum()>0:
                cypher_list.append(column_bool[column_bool].index.values[0])
                cypher_list.append(column)
    return cypher_list

def cypher_transpose(cypher_list,transpose_key):
    transpose_matrix=pd.DataFrame([cypher_list[x:x+len(transpose_key)] for x in range(0,len(cypher_list),len(transpose_key))],columns=[(letter,number) for number,letter in enumerate(transpose_key)])
    debug=pd.DataFrame([cypher_list[x:x+len(transpose_key)] for x in range(0,len(cypher_list),len(transpose_key))],columns=[letter for letter in transpose_key])
    return debug,transpose_matrix[sorted(transpose_matrix.columns)].rename(columns={i:j for i,j in zip(transpose_matrix.columns,[pos[0] for pos in transpose_matrix.columns])})

def cypher_text(matrix):
    c_text="".join(["".join([i if i else " " for i in matrix.T.values[j]]) for j in range(matrix.shape[1])])
    return [c_text[x:x+matrix.shape[0]] for x in range(0,len(c_text),matrix.shape[0])]

# Example 1 (ADFGVX):

In [4]:
text='The war for the Internet has begun. Hollywood is in control of politics. \
The Government is killing innovation.'
key='ANONYMOUS'
transpose_key='MRPRESIDENT'

1. Create <i>Polybius</i> table with key.

In [11]:
table=create_polybius('ANONYMOUS',True)
table

   A  D  F  G  V  X
A  A  1  N  O  Y  M
D  U  S  B  2  C  3
F  D  4  E  5  F  6
G  G  7  H  8  I  9
V  J  0  K  L  P  Q
X  R  T  V  W  X  Z

In [5]:
cypher_matrix=cypher_transpose(cypher_list,transpose_key)
cypher_text(cypher_matrix)

['GXDGAVAAGGDFFVVX ',
 'FGAFFGAFAGDGFFGF ',
 'ADFFDGGGAVGFXGAD ',
 'XAXDGGFVVGXFAVGA ',
 'XAFADFXDXVGFAVGFA',
 'AGFAAAVAGXFXDVFG ',
 'GVGFDFAVXVDAADAGA',
 'DFFADGGGDVVGFDVAG',
 'FAVFFAGAAAVAXVFXF',
 'FXFXFVGDGVDXFGAA ',
 'XFXAAVDFFDFAGGAV ']

2. Replace letters in text according to table.

In [19]:
cypher_list=cypher_table(text,table)
print(["".join(cypher_list[x:x+2]) for x in range(0,len(cypher_list),2)])

['XD', 'GF', 'FF', 'XG', 'AA', 'XA', 'FV', 'AG', 'XA', 'XD', 'GF', 'FF', 'GV', 'AF', 'XD', 'FF', 'XA', 'AF', 'FF', 'XD', 'GF', 'AA', 'DD', 'DF', 'FF', 'GA', 'DA', 'AF', 'GF', 'AG', 'VG', 'VG', 'AV', 'XG', 'AG', 'AG', 'FA', 'GV', 'DD', 'GV', 'AF', 'DV', 'AG', 'AF', 'XD', 'XA', 'AG', 'VG', 'AG', 'FV', 'VV', 'AG', 'VG', 'GV', 'XD', 'GV', 'DV', 'DD', 'XD', 'GF', 'FF', 'GA', 'AG', 'XF', 'FF', 'XA', 'AF', 'AX', 'FF', 'AF', 'XD', 'GV', 'DD', 'VF', 'GV', 'VG', 'VG', 'GV', 'AF', 'GA', 'GV', 'AF', 'AF', 'AG', 'XF', 'AA', 'XD', 'GV', 'AG', 'AF']

3. Build a columnar matrix and fill with replaced text.

In [25]:
step3,cypher_matrix=cypher_transpose(cypher_list,transpose_key)
step3

    M  R  P  R     E     S     I     D     E     N     T
0   X  D  G  F     F     F     X     G     A     A     X
1   A  F  V  A     G     X     A     X     D     G     F
2   F  F  G  V     A     F     X     D     F     F     X
3   A  A  F  F     F     X     D     G     F     A     A
4   D  D  D  F     F     F     G     A     D     A     A
5   F  G  F  A     G     V     G     V     G     A     V
6   X  G  A  G     A     G     F     A     G     V     D
7   D  G  V  A     F     D     V     A     G     A     F
8   X  D  X  A     A     G     V     G     A     G     F
9   V  V  V  A     G     V     G     G     V     X     D
10  G  V  D  V     D     D     X     D     G     F     F
11  F  G  A  A     G     X     F     F     F     X     A
12  A  F  A  X     F     F     A     F     X     D     G
13  V  D  D  V     F     G     V     V     G     V     G
14  G  V  A  F     G     A     G     V     A     F     A
15  F  A  G  X     F     A     A     X     D     G     V
16  A  G  A  F  None  None  None  None  None  None  None

4. Order columnar matrix, with headers in alphabetical order and read output in columns.

In [26]:
cypher_matrix

       D     E     E     I  M     N  P  R  R     S     T
0      G     F     A     X  X     A  G  D  F     F     X
1      X     G     D     A  A     G  V  F  A     X     F
2      D     A     F     X  F     F  G  F  V     F     X
3      G     F     F     D  A     A  F  A  F     X     A
4      A     F     D     G  D     A  D  D  F     F     A
5      V     G     G     G  F     A  F  G  A     V     V
6      A     A     G     F  X     V  A  G  G     G     D
7      A     F     G     V  D     A  V  G  A     D     F
8      G     A     A     V  X     G  X  D  A     G     F
9      G     G     V     G  V     X  V  V  A     V     D
10     D     D     G     X  G     F  D  V  V     D     F
11     F     G     F     F  F     X  A  G  A     X     A
12     F     F     X     A  A     D  A  F  X     F     G
13     V     F     G     V  V     V  D  D  V     G     G
14     V     G     A     G  G     F  A  V  F     A     A
15     X     F     D     A  F     G  G  A  X     A     V
16  None  None  None  None  A  None  A  G  F  None  None

In [27]:
cypher_text(cypher_matrix)

['GXDGAVAAGGDFFVVX ',
 'FGAFFGAFAGDGFFGF ',
 'ADFFDGGGAVGFXGAD ',
 'XAXDGGFVVGXFAVGA ',
 'XAFADFXDXVGFAVGFA',
 'AGFAAAVAGXFXDVFG ',
 'GVGFDFAVXVDAADAGA',
 'DFFADGGGDVVGFDVAG',
 'FAVFFAGAAAVAXVFXF',
 'FXFXFVGDGVDXFGAA ',
 'XFXAAVDFFDFAGGAV ']

# Example 2 (ADFGX):

In [28]:
text2="Attack at once"
key2='BTALPDHOZKQFVSNGICUXMREWY'
transpose_key2='CARGO'

table2=create_polybius(key2,False)
cypher_list2=cypher_table(text2,table2)
step3,cypher_matrix2=cypher_transpose(cypher_list2,transpose_key2)

In [29]:
cypher_text(cypher_matrix2)

['FAXDF', 'ADDDG', 'DGFFF', 'AFAX ', 'AFAFX']

# Example 3 (ADFGVX, with numbers):

In [32]:
text3='attack at 1200am'
key3='NACHTBOMEWRPDFGIJKLQSUVXYZ'
transpose_key3='PRIVACY'

table3=create_polybius(key3,True)
cypher_list3=cypher_table(text3,table3)
step3,cypher_matrix3=cypher_transpose(cypher_list3,transpose_key3)

In [33]:
cypher_text(cypher_matrix3)

['DGDD', 'DAGD', 'DGAF', 'ADDF', 'DADV', 'DVFA', 'ADVX']